version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"  # FastAPI
      - "4173:4173"  # Vite preview
    volumes:
      - ./data:/app/data  # Persist SQLite database
    environment:
      - NODE_ENV=production 